Issues consolidations UX
bringauto/packager pull request #28
Opened 2024-10-23 08:03 UTC by mikusaq

Main issues:

- [ ] Unit tests
- [ ] Rebuild all packages which depend on it
- [ ] Enable only the exactly one version of the package to be stored in git-lfs
- [ ] Create a sysroot from all packages using unpacking zip files of packages
 
Other improvements:

- [ x] Change default image to debian12

2025-01-08 08:48 UTC, mikusaq commented on bap-builder/SysrootMode.go
> +		if err == nil { // Package exists in Git Lfs
Not needed. The sysroot should be created based on current packages in Git Lfs. Probably some packages will be missing in Git Lfs, this would create a lot of warning logs. Will be tested and changes will be made if necessary.

2025-01-08 09:16 UTC, mikusaq commented on modules/bringauto_sysroot/BuiltPackages.go
> +}
Not needed. The function is not called twice with same package.

2025-01-08 09:30 UTC, mikusaq commented on bap-builder/SysrootMode.go
> +	}
Done.

2025-01-08 09:31 UTC, mikusaq commented on bap-builder/SysrootMode.go
> +	defer f.Close()
Done.

2025-01-08 09:31 UTC, mikusaq commented on bap-builder/CmdArgs.go
> +			Default:  false,
Option is required, so I completely removed the default value. Done.

2025-01-08 09:32 UTC, mikusaq commented on modules/bringauto_repository/GitLFSRepository.go
> +	}
Done.

2025-01-08 09:33 UTC, mikusaq commented on bap-builder/PackageMode.go
> +	for _, config := range configList {
Done.

2025-01-08 09:33 UTC, mikusaq commented on bap-builder/PackageMode.go
> +	handleRemover()
Done.

2025-01-08 09:33 UTC, mikusaq commented on modules/bringauto_sysroot/BuiltPackages.go
> +}
Done.

2025-01-08 10:10 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +	return packsToBuild, nil
Done.

2025-01-08 10:11 UTC, mikusaq commented on bap-builder/SysrootMode.go
> +	err := os.MkdirAll(*cmdLine.Repo, 0766)
Removed the whole Git Lfs directory creation, it is redundant. Done.

2025-01-08 11:15 UTC, mikusaq commented on bap-builder/SysrootMode.go
> +	}
Done.

2025-01-08 11:15 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +	}
Done.

2025-01-15 10:33 UTC, mikusaq commented on modules/bringauto_sysroot/default_test.go
> +}
Done.

2025-01-21 11:34 UTC, koudis commented on example/docker/fedora41/Dockerfile
> +RUN echo "export CMLIB_DIR=/cmakelib" >> /root/.bashrc
Not needed.

2025-01-21 11:34 UTC, koudis commented on example/docker/fedora41/Dockerfile
> +RUN ssh-keygen -A
No needed. It is local Docker file.

2025-01-22 09:11 UTC, mikusaq commented on modules/bringauto_repository/default_test.go
> +}
Not needed.

2025-01-22 09:45 UTC, mikusaq commented on modules/bringauto_repository/default_test.go
> +	}
Not needed, would break deleteGitRepo call.

2025-01-22 09:48 UTC, mikusaq commented on modules/bringauto_sysroot/default_test.go
> +	}
Done.

2025-01-22 09:49 UTC, mikusaq commented on modules/bringauto_sysroot/default_test.go
> +	}
Done.

2025-01-22 09:49 UTC, mikusaq commented on modules/bringauto_repository/default_test.go
> +	deletePackages()
Done.

2025-01-22 09:49 UTC, mikusaq commented on modules/bringauto_repository/default_test.go
> +	repo.CommitAllChanges()
Done.

2025-01-29 14:23 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +}
Done.

2025-01-29 14:27 UTC, koudis commented on example/docker/fedora41/Dockerfile
> +RUN echo root:1234 | chpasswd
It is internal Docker file. It will not be deployed. It serve only for local build env.

2025-01-29 14:39 UTC, koudis commented on example/docker/fedora41/Dockerfile
> +RUN ssh-keygen -A
It is valid approach. These Dockerfiles are not published. It is used locally as a build environment.

2025-01-31 16:52 UTC, mikusaq commented on doc/README.md
> +[Git Repository]:                  ./UseCaseScenarios.md
Done.

2025-01-31 16:59 UTC, mikusaq commented on doc/ContextStructure.md
> +[ConfigStructure]: ./ConfigStructure.md
This is not release log. Not needed.

2025-02-02 12:32 UTC, mikusaq commented on doc/Sysroot.md
> +files are copied to new sysroot directory. Because of the sysroot consistency mechanism this new sysroot will also be consistent.
Not needed.

2025-02-02 12:57 UTC, mikusaq commented on doc/ReliablePackageSource.md
> +build complete Package repository from scratch.
Done.

2025-02-04 09:36 UTC, mikusaq commented on doc/UseCaseScenarios.md
> +Build all dependencies (J, K, L) of the Package (F) before the Package (F) is build.
Done.

2025-02-04 09:36 UTC, mikusaq commented on doc/UseCaseScenarios.md
> +It expects all Package dependencies are already build and installed into build sysroot directory.
Done.

2025-02-05 09:24 UTC, koudis requested changes

2025-02-05 12:39 UTC, mikusaq commented on doc/PlatformString.md
> +Platform string is a string in form `DISTRO_NAME` - `DISTRO_VERSION` - `MACHINE`. It is used for
Done. Is it ok like that?

2025-02-05 12:40 UTC, mikusaq commented on doc/Sysroot.md
> +During Package builds, the Package build files are copied to sysroot directory (`install_sysroot`).
Done. Is it ok like that?

2025-02-05 12:40 UTC, mikusaq commented on doc/PackageRepository.md
> +At the start of `build-package` and `create-sysroot` commands the Package Repository consistency
Done. Is it ok like that?

2025-02-12 09:33 UTC, mikusaq commented on doc/Sysroot.md
> +Repository.
Done.

2025-02-12 09:39 UTC, mikusaq commented on modules/bringauto_testing/Common.go
> +}
Not needed.

2025-02-19 09:52 UTC, koudis commented on bap-builder/PackageMode.go
> +	handleRemover := bringauto_process.SignalHandlerAddHandler(repo.RestoreAllChanges)
Why we do not use deffer here?

2025-02-19 09:52 UTC, koudis commented on modules/bringauto_build/Build.go
> +type buildInitArgs struct {
The question is if it is needed. It is an internal struct.

2025-02-19 09:52 UTC, koudis commented on modules/bringauto_sysroot/BuiltPackages.go
> +	Packages []string
Maybe not needed, it is self descriptive....

2025-02-19 11:52 UTC, mikusaq commented on modules/bringauto_build/Build.go
> +type buildInitArgs struct {
I think it is not needed, it is also the same naming scheme as for other InitArgs structs for bringauto_prerequisities functions.

2025-02-19 11:57 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +		for _, dep := range packConfig.DependsOn {
What do you mean? It is already splitted on 2 lines.

2025-02-19 12:08 UTC, koudis commented on doc/Sysroot.md
> +During Package builds, the Package build files are copied to sysroot directory (`install_sysroot`).
Yes. It is.

2025-02-19 12:08 UTC, koudis commented on modules/bringauto_build/Build.go
> +type buildInitArgs struct {
ook.

2025-02-19 12:12 UTC, koudis commented on doc/PlatformString.md
> +Platform string is a string in form `DISTRO_NAME` - `DISTRO_VERSION` - `MACHINE`. It is used for
Yes, thanks

2025-02-19 12:26 UTC, koudis commented on modules/bringauto_context/ContextManager.go
> +		for _, dep := range packConfig.DependsOn {
No I mean the whole function. It isn't very easy and it is not easy to read it and understand it. Maybe split the whole function into two?

2025-02-19 12:30 UTC, mikusaq commented on modules/bringauto_sysroot/BuiltPackages.go
> +	Packages []string
I agree, the doc there should explain it enough, right?

2025-02-19 12:41 UTC, mikusaq commented on bap-builder/PackageMode.go
> +	handleRemover := bringauto_process.SignalHandlerAddHandler(repo.RestoreAllChanges)
True, done.

2025-02-19 12:42 UTC, mikusaq commented on modules/bringauto_repository/GitLFSRepository.go
> +		"*",
No difference, I changed it back.

2025-02-19 12:43 UTC, mikusaq commented on modules/bringauto_log/Handler.go
> +	orange = 33
I have added the ANSI mention. Done.

2025-02-19 12:43 UTC, mikusaq commented on modules/bringauto_docker/Docker.go
> +	defaultImageNameConst = "debian12"
Done.

2025-02-19 14:32 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +		for _, dep := range packConfig.DependsOn {
Ok, done.

2025-02-19 14:33 UTC, mikusaq commented on README.md
> +    bap-builder build-package --context ./example --image-name debian12 --output-dir ./lfsrepo --all
Not needed, information updated in docs.

2025-02-20 14:57 UTC, koudis approved these changes
It seems ok.
Can we release new major version? We did breaking changes...

2025-02-21 09:57 UTC, mikusaq commented on modules/bringauto_context/ContextManager.go
> +				context.addDependsOnPackagesToBuild(&packsToBuild, packConfig, visited, recursively)
Done.

2025-02-21 10:02 UTC, merged